package uk.gov.justice.digital.hmpps.communitysupportapi.service

import org.slf4j.LoggerFactory
import org.springframework.stereotype.Service
import uk.gov.justice.digital.hmpps.communitysupportapi.mapper.toDomain
import uk.gov.justice.digital.hmpps.communitysupportapi.model.Person
import uk.gov.justice.digital.hmpps.communitysupportapi.model.PersonIdentifier
import uk.gov.justice.digital.hmpps.communitysupportapi.validation.PersonIdentifierValidator

@Service
class PersonService(
  private val deliusService: DeliusService,
  private val nomisService: NomisService,
  private val identifierValidator: PersonIdentifierValidator,
) {
  companion object {
    private val log = LoggerFactory.getLogger(this::class.java)
  }

  fun getPerson(crnOrPrisonerNumber: String): Person {
    log.info("Received Person lookup request for identifier [{}]", crnOrPrisonerNumber)

    return when (val identifier = identifierValidator.validate(crnOrPrisonerNumber)) {
      is PersonIdentifier.Crn -> deliusService.getPersonDetailsByCrn(identifier.value).toDomain()
      is PersonIdentifier.PrisonerNumber -> {
        val nomisPersonDto = nomisService.getPersonDetailsByPrisonerNumber(identifier.value)
        /*
         Create CachedPersonDetails Object, then store in database

         CachedPersonDetails
           id: "abc-123"                     // generated by database
           created_at: "2025-12-10T11:20Z"   timestamp.now()
           first_name: "Joe"                 NomisPersonDto.firstName
           last_name: "Blogs"                NomisPersonDto.lastName
           identifier: "X123"                PersonIdentifier.PrisonerNumber.value
           identifier_type: "CRN"            "PrisonerNumber"
           most_recent_sentence_date: "2020-01-01"
        */

        nomisPersonDto.toDomain()
      }

    }
  }
}
