package uk.gov.justice.digital.hmpps.communitysupportapi.dto.nomis

import uk.gov.justice.digital.hmpps.communitysupportapi.dto.PhoneNumberDto
import java.time.LocalDate

data class NomisPersonDto(
  val prisonerNumber: String,
  val pncNumber: String? = null,
  val pncNumberCanonicalShort: String? = null,
  val pncNumberCanonicalLong: String? = null,
  val croNumber: String? = null,
  val bookingId: String? = null,
  val bookingNumber: String? = null,
  val title: String? = null,
  val firstName: String,
  val lastName: String,
  val dateOfBirth: LocalDate,
  val gender: String = "Unknown",
  val ethnicity: String? = null,
  val raceCode: String? = null,
  val requiresInterpreter: Boolean = false,
  val maritalStatus: String? = null,
  val religion: String? = null,
  val nationality: String? = null,
  val smoker: String? = null,
  val personalCareNeeds: List<PersonalCareNeedsDto> = emptyList(),
  val languages: List<LanguagesDto> = emptyList(),
  val currentFacialImageId: Int? = null,
  val militaryRecord: Boolean = false,
  val status: String? = null,
  val lastMovementTypeCode: String? = null,
  val lastMovementReasonCode: String? = null,
  val inOutStatus: String? = null,
  val prisonId: String? = null,
  val prisonName: String? = null,
  val lastPrisonId: String? = null,
  val previousPrisonId: String? = null,
  val previousPrisonLeavingDate: LocalDate? = null,
  val cellLocation: String? = null,
  val aliases: List<AliasesDto> = emptyList(),
  val alerts: List<AlertsDto> = emptyList(),
  val csra: String? = null,
  val category: String? = null,
  val complexityOfNeedLevel: String? = null,
  val legalStatus: String? = null,
  val imprisonmentStatus: String? = null,
  val imprisonmentStatusDescription: String? = null,
  val convictedStatus: String? = null,
  val mostSeriousOffence: String? = null,
  val recall: Boolean = false,
  val indeterminateSentence: Boolean = false,
  val sentenceStartDate: LocalDate? = null,
  val releaseDate: LocalDate? = null,
  val confirmedReleaseDate: LocalDate? = null,
  val sentenceExpiryDate: LocalDate? = null,
  val licenceExpiryDate: LocalDate? = null,
  val homeDetentionCurfewEligibilityDate: LocalDate? = null,
  val homeDetentionCurfewActualDate: LocalDate? = null,
  val homeDetentionCurfewEndDate: LocalDate? = null,
  val topupSupervisionStartDate: LocalDate? = null,
  val topupSupervisionExpiryDate: LocalDate? = null,
  val additionalDaysAwarded: Int? = null,
  val nonDtoReleaseDate: LocalDate? = null,
  val nonDtoReleaseDateType: String? = null,
  val receptionDate: LocalDate? = null,
  val lastAdmissionDate: LocalDate? = null,
  val paroleEligibilityDate: LocalDate? = null,
  val automaticReleaseDate: LocalDate? = null,
  val postRecallReleaseDate: LocalDate? = null,
  val conditionalReleaseDate: LocalDate? = null,
  val nonParoleDate: LocalDate? = null,
  val actualParoleDate: LocalDate? = null,
  val tariffDate: LocalDate? = null,
  val releaseOnTemporaryLicenceDate: LocalDate? = null,
  val locationDescription: String? = null,
  val restrictedPatient: Boolean = false,
  val supportingPrisonId: String? = null,
  val dischargedHospitalId: String? = null,
  val dischargedHospitalDescription: String? = null,
  val dischargeDate: LocalDate? = null,
  val dischargeDetails: String? = null,
  val currentIncentive: CurrentIncentiveDto? = null,
  val heightCentimetres: Int? = null,
  val weightKilograms: Int? = null,
  val hairColour: String? = null,
  val rightEyeColour: String? = null,
  val leftEyeColour: String? = null,
  val facialHair: String? = null,
  val shapeOfFace: String? = null,
  val build: String? = null,
  val shoeSize: Int? = null,
  val tattoos: List<BodyPartCommentDto> = emptyList(),
  val scars: List<BodyPartCommentDto> = emptyList(),
  val marks: List<BodyPartCommentDto> = emptyList(),
  val addresses: List<AddressesDto> = emptyList(),
  val emailAddresses: List<EmailAddressesDto> = emptyList(),
  val phoneNumbers: List<PhoneNumberDto> = emptyList(),
  val identifiers: List<IdentifiersDto> = emptyList(),
  val allConvictedOffences: List<AllConvictedOffencesDto> = emptyList(),
)
