package uk.gov.justice.digital.hmpps.communitysupportapi.dto

typealias ActionPlanSessionDeliveryDetailsRequest = ActionPlanStepDetailsRequest
typealias ActionPlanSessionDeliveryDetailsResponse = ActionPlanStepDetailsResponse
typealias SessionDeliveryQuestionRequest = ActionPlanStepQuestionRequest
typealias SessionDeliveryQuestion = ActionPlanStepQuestion
